// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "toss_boys_2_prologue_anim_cells.inc.c"

struct Animation anim_toss_boys_2_prologue_title[] = {
    /* 000 */ { toss_boys_2_prologue_cel000, 40 },
    /* 001 */ { toss_boys_2_prologue_cel001, 6 },
    /* 002 */ { toss_boys_2_prologue_cel002, 6 },
    /* 003 */ { toss_boys_2_prologue_cel003, 6 },
    /* 004 */ { toss_boys_2_prologue_cel004, 6 },
    /* 005 */ { toss_boys_2_prologue_cel005, 6 },
    /* 006 */ { toss_boys_2_prologue_cel006, 6 },
    /* 007 */ { toss_boys_2_prologue_cel007, 94 },
    /* 008 */ END_ANIMATION,
};

