// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "drum_lessons_menu_anim_cells.inc.c"

struct Animation anim_lessons_menu_short_1[] = {
    /* 000 */ { drum_lessons_menu_cel007, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_rank_s[] = {
    /* 000 */ { drum_lessons_menu_cel001, 5 },
    /* 001 */ { drum_lessons_menu_cel003, 5 },
    /* 002 */ { drum_lessons_menu_cel002, 5 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_rank_a[] = {
    /* 000 */ { drum_lessons_menu_cel004, 40 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_rank_b[] = {
    /* 000 */ { drum_lessons_menu_cel005, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_rank_c[] = {
    /* 000 */ { drum_lessons_menu_cel006, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_2[] = {
    /* 000 */ { drum_lessons_menu_cel008, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_3[] = {
    /* 000 */ { drum_lessons_menu_cel009, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_4[] = {
    /* 000 */ { drum_lessons_menu_cel010, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_5[] = {
    /* 000 */ { drum_lessons_menu_cel011, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_6[] = {
    /* 000 */ { drum_lessons_menu_cel012, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_7[] = {
    /* 000 */ { drum_lessons_menu_cel013, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_8[] = {
    /* 000 */ { drum_lessons_menu_cel014, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_short_9[] = {
    /* 000 */ { drum_lessons_menu_cel015, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_long_1[] = {
    /* 000 */ { drum_lessons_menu_cel016, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_long_2[] = {
    /* 000 */ { drum_lessons_menu_cel017, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_long_3[] = {
    /* 000 */ { drum_lessons_menu_cel018, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_long_4[] = {
    /* 000 */ { drum_lessons_menu_cel019, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_long_5_6[] = {
    /* 000 */ { drum_lessons_menu_cel020, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_hi_tech_1_2[] = {
    /* 000 */ { drum_lessons_menu_cel021, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_hi_tech_unused[] = {
    /* 000 */ { drum_lessons_menu_cel021, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_basic_1[] = {
    /* 000 */ { drum_lessons_menu_cel022, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_basic_2[] = {
    /* 000 */ { drum_lessons_menu_cel023, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_basic_3[] = {
    /* 000 */ { drum_lessons_menu_cel024, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_lessons_menu_tanuki_and_monkey[] = {
    /* 000 */ { drum_lessons_menu_cel025, 4 },
    /* 001 */ END_ANIMATION,
};

