// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel rhythm_tweezers_prologue_cel004[] = {
    /* Len */ 3,
    /* 000 */ 0x40e0, 0xc1c8, 0x4000,
    /* 001 */ 0x00e0, 0x8008, 0x4008,
    /* 002 */ 0x80e0, 0x4028, 0x400c
};

AnimationCel rhythm_tweezers_prologue_cel001[] = {
    /* Len */ 3,
    /* 000 */ 0x40e0, 0xc1c8, 0x1000,
    /* 001 */ 0x00e0, 0x8008, 0x1008,
    /* 002 */ 0x80e0, 0x4028, 0x100c
};

AnimationCel rhythm_tweezers_prologue_cel008[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x100e,
    /* 001 */ 0x4000, 0x8020, 0x1012
};

AnimationCel rhythm_tweezers_prologue_cel000[] = {
    /* Len */ 3,
    /* 000 */ 0x40e0, 0xc1c8, 0x0000,
    /* 001 */ 0x00e0, 0x8008, 0x0008,
    /* 002 */ 0x80e0, 0x4028, 0x000c
};

AnimationCel rhythm_tweezers_prologue_cel009[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x000e,
    /* 001 */ 0x4000, 0x8020, 0x0012
};

AnimationCel rhythm_tweezers_prologue_cel007[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x200e,
    /* 001 */ 0x4000, 0x8020, 0x2012
};

AnimationCel rhythm_tweezers_prologue_cel006[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x300e,
    /* 001 */ 0x4000, 0x8020, 0x3012
};

AnimationCel rhythm_tweezers_prologue_cel002[] = {
    /* Len */ 3,
    /* 000 */ 0x40e0, 0xc1c8, 0x2000,
    /* 001 */ 0x00e0, 0x8008, 0x2008,
    /* 002 */ 0x80e0, 0x4028, 0x200c
};

AnimationCel rhythm_tweezers_prologue_cel005[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x400e,
    /* 001 */ 0x4000, 0x8020, 0x4012
};

AnimationCel rhythm_tweezers_prologue_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x40e0, 0xc1c8, 0x3000,
    /* 001 */ 0x00e0, 0x8008, 0x3008,
    /* 002 */ 0x80e0, 0x4028, 0x300c
};

