// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel polyrhythm_2_prologue_cel000[] = {
    /* Len */ 3,
    /* 000 */ 0x00fc, 0x01fc, 0x0018,
    /* 001 */ 0x40f4, 0xc00d, 0x0100,
    /* 002 */ 0x80f4, 0x404d, 0x0108
};

AnimationCel polyrhythm_2_prologue_cel001[] = {
    /* Len */ 5,
    /* 000 */ 0x40f4, 0xc00d, 0x0100,
    /* 001 */ 0x80f4, 0x404d, 0x0108,
    /* 002 */ 0x00d0, 0xc000, 0x0010,
    /* 003 */ 0x00d0, 0xc040, 0x0000,
    /* 004 */ 0x00d0, 0xc1c0, 0x0008
};

