// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

Palette disclamer_pal[] = {
    /* PALETTE 00 */ {
        /* 00 */ TO_RGB555(0xffffff),
        /* 01 */ TO_RGB555(0xffef00),
        /* 02 */ TO_RGB555(0xf7ce3f),
        /* 03 */ TO_RGB555(0xadb5b5),
        /* 04 */ TO_RGB555(0xffa518),
        /* 05 */ TO_RGB555(0x7b9cde),
        /* 06 */ TO_RGB555(0xf75a18),
        /* 07 */ TO_RGB555(0x009cf7),
        /* 08 */ TO_RGB555(0x4a6352),
        /* 09 */ TO_RGB555(0x3942d6),
        /* 10 */ TO_RGB555(0xa53110),
        /* 11 */ TO_RGB555(0xff0000),
        /* 12 */ TO_RGB555(0x1842ad),
        /* 13 */ TO_RGB555(0x08215a),
        /* 14 */ TO_RGB555(0x100008),
        /* 15 */ TO_RGB555(0x000000)
    }
};
